export type {
  AppSettings,
  CoreState,
  CoreStatus,
  Profile,
  ProfilesState,
  ProxyMode,
  ProxyNode,
  ProxiesResponse,
  ConnectionsSnapshot,
  ConnectionItem,
  RuleItem,
  LogLine,
  TrafficSnapshot,
  LogLevel,
  DnsSettings,
  DnsEnhancedMode,
  HotkeySettings,
  ProviderInfo,
  ProvidersResponse,
  RequestItem,
  GeoResourceFile,
  WebDavSettings,
} from "../../../electron/shared/types";

// Profile.scriptId is part of Profile type from shared types
