export type {
  AppSettings,
  CoreState,
  CoreStatus,
  Profile,
  ProfilesState,
  ProxyMode,
  ProxyNode,
  ProxiesResponse,
  ConnectionsSnapshot,
  ConnectionItem,
  RuleItem,
  LogLine,
  TrafficSnapshot,
  LogLevel,
  DnsSettings,
  DnsEnhancedMode,
  HotkeySettings,
  ProviderInfo,
  ProvidersResponse,
  RequestItem,
  GeoResourceFile,
  WebDavSettings,
  CustomProxyGroup,
  PortSettings,
  OnDemandSettings,
  DashboardLayout,
  DashboardWidgetId,
  ThemePreset,
  UpdateCheckResult,
} from "../../../electron/shared/types";

export {
  THEME_PRESETS,
  DEFAULT_PORTS,
  DEFAULT_ON_DEMAND,
  DEFAULT_DASHBOARD,
} from "../../../electron/shared/types";
