/**
 * Typed IPC channel registry — single source of truth for channel strings.
 * main.ts and preload.ts should prefer these constants over raw strings.
 */
export const IpcChannels = {
  // core
  "core:state": "core:state",
  "core:start": "core:start",
  "core:stop": "core:stop",
  "core:restart": "core:restart",
  "core:reload": "core:reload",
  // settings
  "settings:get": "settings:get",
  "settings:update": "settings:update",
  // profiles
  "profiles:list": "profiles:list",
  "profiles:add-url": "profiles:add-url",
  "profiles:add-file": "profiles:add-file",
  "profiles:update": "profiles:update",
  "profiles:delete": "profiles:delete",
  "profiles:set-current": "profiles:set-current",
  "profiles:rename": "profiles:rename",
  "profiles:edit": "profiles:edit",
  "profiles:content": "profiles:content",
  "profiles:save-content": "profiles:save-content",
  "profiles:set-prepend-rules": "profiles:set-prepend-rules",
  "profiles:set-script": "profiles:set-script",
  "profiles:set-custom-groups": "profiles:set-custom-groups",
  "profiles:set-custom-rules": "profiles:set-custom-rules",
  "profiles:set-append-rules": "profiles:set-append-rules",
  "profiles:set-custom-proxies": "profiles:set-custom-proxies",
  "profiles:set-custom-proxy-providers": "profiles:set-custom-proxy-providers",
  "profiles:reorder": "profiles:reorder",
  "profiles:merged-preview": "profiles:merged-preview",
  "profiles:import-clipboard": "profiles:import-clipboard",
  // scripts
  "scripts:list": "scripts:list",
  "scripts:create": "scripts:create",
  "scripts:rename": "scripts:rename",
  "scripts:content": "scripts:content",
  "scripts:save": "scripts:save",
  "scripts:delete": "scripts:delete",
  "scripts:default": "scripts:default",
  // api
  "api:proxies": "api:proxies",
  "api:select-proxy": "api:select-proxy",
  "api:delay": "api:delay",
  "api:connections": "api:connections",
  "api:close-connection": "api:close-connection",
  "api:close-all-connections": "api:close-all-connections",
  "api:rules": "api:rules",
  "api:providers": "api:providers",
  "api:update-provider": "api:update-provider",
  "api:healthcheck-provider": "api:healthcheck-provider",
  "api:flush-fakeip": "api:flush-fakeip",
  "api:flush-dns": "api:flush-dns",
  "api:upgrade-geo": "api:upgrade-geo",
  "api:set-mode": "api:set-mode",
  "api:patch-configs": "api:patch-configs",
  "api:credentials": "api:credentials",
  // requests
  "requests:list": "requests:list",
  "requests:clear": "requests:clear",
  // geo
  "geo:list": "geo:list",
  "geo:download": "geo:download",
  "geo:download-all": "geo:download-all",
  // webdav
  "webdav:test": "webdav:test",
  "webdav:upload": "webdav:upload",
  "webdav:download": "webdav:download",
  // system
  "system:proxy": "system:proxy",
  "system:authorize-tun": "system:authorize-tun",
  "system:enable-loopback": "system:enable-loopback",
  "system:copy-proxy-env": "system:copy-proxy-env",
  "system:public-ip": "system:public-ip",
  "system:network-check": "system:network-check",
  "system:dns": "system:dns",
  // app
  "app:paths": "app:paths",
  "app:open-path": "app:open-path",
  "app:show-item": "app:show-item",
  "app:copy-text": "app:copy-text",
  "app:get-version": "app:get-version",
  "app:check-update": "app:check-update",
  "app:check-app-update": "app:check-app-update",
  "app:download-update": "app:download-update",
  "app:quit-and-install": "app:quit-and-install",
  "app:open-devtools": "app:open-devtools",
  "app:save-text": "app:save-text",
  // backup / config
  "backup:create": "backup:create",
  "backup:restore": "backup:restore",
  "config:runtime": "config:runtime",
  "config:save-runtime": "config:save-runtime",
} as const;

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels];
